### ISSUE TITLE
Build failing on missing kodi/addon-instance/ShaderPreset.h

### ISSUE THREAD

**Issue by davidheitman** [VelocityRa/game.shader.presets#18]
Building against xbmc master or garbear's retroplayer branch both produce the same results, a failed build with the following error:

> In file included from /home/loucipher/repos/Lou-Cipher/xbmc/kodi-addon/build/game.shader.presets/src/addon.cpp:22:0:
/home/loucipher/repos/Lou-Cipher/xbmc/kodi-addon/build/game.shader.presets/src/addon.h:23:10: fatal error: kodi/addon-instance/ShaderPreset.h: No such file or directory
 #include <kodi/addon-instance/ShaderPreset.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/game.shader.presets.dir/build.make:62: recipe for target 'CMakeFiles/game.shader.presets.dir/src/addon.cpp.o' failed
make[5]: *** [CMakeFiles/game.shader.presets.dir/src/addon.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/game.shader.presets.dir/all' failed
make[4]: *** [CMakeFiles/game.shader.presets.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/game.shader.presets.dir/build.make:112: recipe for target 'game.shader.presets-prefix/src/game.shader.presets-stamp/game.shader.presets-build' failed
make[2]: *** [game.shader.presets-prefix/src/game.shader.presets-stamp/game.shader.presets-build] Error 2
CMakeFiles/Makefile2:9845: recipe for target 'CMakeFiles/game.shader.presets.dir/all' failed
make[1]: *** [CMakeFiles/game.shader.presets.dir/all] Error 2

I don't see this header as actually existing anywhere.

**Comment by VelocityRa** [comment]
You have to use garbear's `feature_shaders` branch or one of my newer branches.
It looks like you're trying to run this on Linux, but shaders won't work anyway as the OpenGL port isn't finished yet, only Direct3D 11. They only work on Windows (and possibly Xbox) at the moment.

**Comment by davidheitman** [comment]
Well then, guess this can be closed.
